version: "3.8"

services:
    react:
        build:
            context: ./client
            dockerfile: ./Dockerfile
        ports:
            - "3000:3000"
        container_name: react
        links: 
            - node
        command: "npm run start"
    node:
        build:
            context: ./server
            dockerfile: ./Dockerfile
        ports:
            - "3001:3001"
        container_name: node
        links: 
            - mongo
        command: "npm run backend"
    mongo:
        image: mongo
        container_name: mongo
        ports: 
          - "27017:27017"

