version: "3.8"

services:
    node:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "5000:3001"
        container_name: node
        links: 
            - mongo
    mongo:
        image: mongo
        container_name: mongo
        ports: 
          - "27017:27017"

